labels=[
  "Events",
  "Create event",
  "Customize",
  "Upcoming",
  "Past",
  "Zoom Events",
  "Your Events",
  "0 Event",
  "Enter search string",
  "Select dates",
  "Filters",
  "Title",
  "Date",
  "Time",
  "Location",
  "Type",
  "Recurrence",
  "Status",
  "Bookings",
  "Set default values for any new events to save time.",
  "Customize",
  "Export",
  "All time",
  "12 month",
  "30 days",
  "7 days",
  "0 item",
  "Review and manage all your event bookings here.",
  "Order ID",
  "Order Date/Time",
  "Registrant",
  "Event Title/Location",
  "Occurrence",
  "Paid",
  "Status",
  "Event",
  "Zoom meeting",
  "Apply",
  "Integrations",
  "Connect and manage your integrations to enhance your event management.",
  "Connected",
  "Calendars Integration",
  "Event Integrations",
  "Calendars",
  "Sync your event schedules effortlessly with Google Calendar or Outlook to keep everyone informed.",
  "Manage",
  "Learn More →",
  "Emails Integration",
  "Emails",
  "Automate communications using Google Mail and Microsoft Outlook, ensuring timely updates for your events.",
  "Connect",
  "OAuth Setup Required Before Connecting.",
  "Gmail",
  "Zoom Integration",
  "Video Conferencing",
  "Available on paid plans.",
  "Zoom",
  "Stripe Integration",
  "Stripe",
  "Sync your payments and ticket sales directly via Stripe. (Requires an active subscription plan.)",
  "Email Templates",
  "Easily View, Create, and Modify Email Templates",
  "Save",
  "Cancel",
  "Template Name",
  "In-person Event - Booking",
  "Email Subject",
  "{{event_name}} - {{store_name}}",
  "Template Parameters",
  "Parameter",
  "Description",
  "{{category_details}}",
  "Category details",
  "{{category}}",
  "Category of event",
  "{{custom_field_1_name}}",
  "Custom field 1 name",
  "{{custom_field_1_value}}",
  "Custom field 1 value",
  "{{custom_field_2_name}}",
  "Custom field 2 name",
  "{{custom_field_2_value}}",
  "Custom field 2 value",
  "{{customer_name}}",
  "Customer name",
  "{{date}}",
  "Date of event",
  "{{event_name}}",
  "Event name",
  "{{location_details}}",
  "Location details",
  "{{location_hours}}",
  "Location operational hours",
  "{{location}}",
  "Location of event",
  "{{members_list}}",
  "Event members info list",
  "{{store_email}}",
  "Store contact email",
  "{{store_name}}",
  "Store name",
  "{{time}}",
  "Time of event",
  "Edit Mode",
  "Rich Text",
  "HTML",
  "Email Content",
  "Hi {{customer_name}}, Thank you for registering!",
  "You have been successfully registered to the {{event_name}} event. Please save this email for the event details which are given below",
  "{{date}} {{time}}",
  "{{location}}",
  "{{location_details}}",
  "{{location_hours}}",
  "{{category}}",
  "{{category_details}}",
  "For any queries or to cancel booking please contact the store at {{store_email}}",
  "We look forward to seeing you.",
  "Preview",
  "Subject: {{event_name}} - {{store_name}}",
  "Analytics",
  "View your Revenue, Registrants, Events, and Filter analytics.",
  "Total Revenue",
  "Total Registrants",
  "Events Analytics",
  "Filters Analytics",
  "Select Dates",
  "0",
  "You haven’t made any Sales yet.",
  "Reset",
  "0 Registrants",
  "You don’t have any Registrants yet.",
  "Active Events",
  "Events Happened",
  "Events Cancelled",
  "You don’t have Filter Statistics yet.",
  "Settings",
  "Save",
  "Cancel",
  "Set default values for any new events to save time.",
  "General",
  "Reminders",
  "Billing plans",
  "Fast Checkout",
  "Widget Settings",
  "Widget Translations",
  "Time zone",
  "Set a default time zone.",
  "US/Pacific",
  "Time format",
  "Set a default time format.",
  "12 hours",
  "Hide timezone abbreviation in email, widget and dashboard.",
  "Currency format",
  "Set a default currency.",
  "Alphabets: USD / CAD / CNY",
  "Duration",
  "Set a default event duration.",
  "1 hour",
  "Start / end time",
  "Set a default start and end time.",
  "Start time",
  "End time",
  "Ticket price",
  "Set a default ticket price.",
  "Location",
  "Set a default event location.",
  "Event",
  "Zoom Event",
  "Email notifications",
  "Enable email notifications",
  "First reminder",
  "Enable first reminder and specify time to first reminder",
  "Second reminder",
  "Enable second reminder and specify time to second reminder",
  "Finished reminder",
  "Send notification after the event has ended",
  "Additional Email Notification Settings",
  "Set up extra email alerts and reminders for your events. You can choose to skip staff notifications or add reminder emails at specific times before the event",
  "Additional reminder emails list (comma-separated)",
  "Additional reminder hours",
  "Skip Staff Email Notification",
  "Free",
  "Unlimited Bookings",
  "Events",
  "Fast Checkout",
  "Widgets",
  "Notifications",
  "Multi Booking",
  "Custom Store Email",
  "Recurring",
  "Stripe Integration",
  "Multi Tickets",
  "Zoom",
  "Premium Support",
  "Reminders",
  "Email Customization",
  "User Management",
  "Activated",
  "Premium",
  "Activate",
  "Enable Fast Checkout for Free Events",
  "Activate fast checkout to speed up the booking process for free services",
  "Enable Fast Checkout",
  "Skip Captcha on Fast Checkout",
  "Activate to bypass captcha verification during fast checkout for free services.",
  "Skip Captcha",
  "Marketing Consent Checkbox",
  "Turn on this option to show a checkbox at free checkout, so customers can sign up for marketing emails and newsletters",
  "Marketing Consent"
]