name: Deploy to WordPress.org SVN

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Remove all hidden files and directories
        run: |
          find . -type f -name ".*" ! -name "." ! -name ".." ! -path "./.git/*" -exec rm -f {} +
          find . -type d -name ".*" ! -name "." ! -name ".." ! -path "./.git/*" -exec rm -rf {} +
          echo "All hidden files and directories removed"

      - name: Debug Git repository state
        run: |
          echo "Checking if .git directory exists: $(ls -d .git 2>/dev/null && echo 'Yes' || echo 'No')"
          echo "Git status: $(git status 2>/dev/null || echo 'Not a Git repository')"

      - name: Get latest tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v1.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Using latest tag: $LATEST_TAG"

      - name: Remove .git directory before deployment
        run: |
          rm -rf .git
          echo ".git directory removed"

      - name: Deploy to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: servvai-event-booking
        with:
          generate-zip: true
          tag: ${{ env.LATEST_TAG }}