name: Sync Changelog to Docs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout plugin repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone docs repo
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          # Clone docs repository
          git clone https://$GIT_USERNAME:$GIT_TOKEN@github.com/coderisetechnologiesinc/servvai-docs.git
          cd servvai-docs

          # Backup existing releasenotes.md
          cp changelogs/releasenotes.md changelogs/releasenotes.md.bak

          # Keep first 5 lines and remove everything else
          head -n 5 changelogs/releasenotes.md.bak > changelogs/releasenotes.md

          # Append full plugin CHANGELOG.md from parent repo
          echo "" >> changelogs/releasenotes.md
          cat ../CHANGELOG.md >> changelogs/releasenotes.md

          # Configure git
          git config user.name "$GIT_USERNAME"
          git config user.email "$GIT_EMAIL"

          # Commit and push if there are changes
          if git diff --quiet changelogs/releasenotes.md; then
            echo "No changes to commit."
            exit 0
          fi

          git add changelogs/releasenotes.md
          git commit -m "Sync full CHANGELOG.md for release: ${{ github.event.release.tag_name || 'manual' }}"
          git push